version: 2

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
          # type: approval
          requires:
            - build
      - deploy-gh-pages:
          requires:
            - test


jobs:
  build:
    docker:
      - image: circleci/node:9.9
    steps:
      - checkout # Checks out the source code
      - run: echo "starting build job"
      - run:
          name: Install Dependencies
          command: npm i
      - run:
          name: build
          command: npm run build
      - store_artifacts:
          path: build-results

  test:
    docker:
      - image: circleci/node:9.9
    steps:
      - checkout # Checks out the source code
      - run: echo "starting test job"
      - run:
          name: Install Dependencies
          command: npm i
      - run:
          name: test
          command: npm run test
      - store_artifacts:
          path: test-results

  deploy:
    docker:
      - image: circleci/node:9.9
    steps:
      - checkout # Checks out the source code
      - run: echo "starting deploy"
      - run:
          name: Install Dependencies
          command: npm i
      - run:
          name: deploy
          command: npm run deploy
      - store_artifacts:
          path: test-results










